language: csharp

os:
  - linux
  - osx

mono:
  - latest
  - 4.4.2
  - 4.2.2

sudo: false

install:

script: 
  - ./build.sh NuGet

# Fails on Travis Linux Mono latest (4.6.1) because FSharp.Core PCLs are not installed, see
# https://github.com/fsharp/fsharp/issues/623#issuecomment-253165838

matrix:
  allow_failures:
    - os: linux
      mono: latest
    - os: osx
      mono: 4.4.2


