language: csharp

os:
  - linux
  - osx

mono:
  - weekly
  - latest
  - 4.8.0
  - 4.4.2


sudo: false

install:

script: 
  - ./fcs/build.sh Test.NetFx

# Fails on Travis OSX too often because there are network outages on that configuration getting the Mono MDK


matrix:
  exclude:
    - os: osx
      mono: 4.4.2
    - os: osx
      mono: 4.8.0

