language: csharp

os:
  - linux
  - osx

mono:
  - latest
  - 4.2.2

sudo: false

install:

script: 
  - ./build.sh NuGet

# See bug "https://bugzilla.xamarin.com/show_bug.cgi?id=41914"
# peverify failing on Mono latest with "condition `res != EINVAL' not met"

matrix:
  allow_failures:
    - mono: latest


