os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

environment:
  global:
    CLI_VERSION: 1.0.0-preview1-002702 # released preview1
  matrix:
    - BUILD_TARGET: DotnetCliTests
    - BUILD_TARGET: NuGet

install:
  # .NET Core SDK binaries
  - ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
  # Download .NET Core SDK and add to PATH
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFile = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - ps: dotnet --info
  - cmd: build.cmd %BUILD_TARGET%

test: off
version: '{build}'
artifacts:
  - path: bin\*.nupkg
