os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - BUILD_TARGET: NuGet
    - BUILD_TARGET: Nuget.AddNetCore

matrix:
  allow_failures:
    - BUILD_TARGET: Nuget.AddNetCore
    
build_script:
  - ps: dotnet --info
  - cmd: build.cmd %BUILD_TARGET%

test: off
version: '{build}'
artifacts:
  - path: bin\*.nupkg
