name: Build

on: [push, pull_request]

jobs:
  build:

    # FCS tests fail for netfx on macos/ubuntu, so we encode that here.
    continue-on-error: ${{ matrix.knownFailure }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet: [3.1.301] # TODO: wish this action didn't pin versions...
        include:
          - os: windows-latest
            knownFailure: false
          - os: macos-latest
            knownFailure: true
          - os: ubuntu-latest
            knownFailure: true
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnet}}
    - name: Restore tools
      run: dotnet tool restore
      working-directory: ./fcs
    - name: Build and test
      run: dotnet fake build -t TestAndNuGet
      working-directory: ./fcs
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: code-coverage-report-${{ matrix.os }}-${{ env.GITHUB_SHA }}
        path: ${{ github.workspace }}/artifacts/TestResults/Release/FSharp.Compiler.Service.Test.*.xml