name: Build

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet: [3.1.201] # TODO: wish this action didn't pin versions...
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnet}}
    - name: Restore tools
      run: dotnet tool restore
      working-directory: ./fcs
    - name: Build and test
      run: dotnet fake build -t TestAndNuGet
      working-directory: ./fcs
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: ${{ github.workspace }}/artifacts/TestResults/Release/FSharp.Compiler.Service.Test.*.xml